mixed threshold docs
csgenetics/csgenetics_scrnaseq pull request #24
Opened 2024-11-11 10:08 UTC by woodsl92

Added description of mixed-species cell-caller behaviour, and L-plot examples.

2024-11-12 10:21 UTC, ImogenCarruthersCS submitted a review, later dismissed

2024-11-12 10:21 UTC, ImogenCarruthersCS commented on README.md
> +The Cell Caller algorithm is run on each of the candidate subpopulations to set a minimum count threshold for each species. Once the species-specific minimum count thresholds are defined we use them
Please double check that the cell caller section uses exact and correct language throughout. For example, here, this should refer to splitting the entire pool of barcodes into 4 groups, not cells.

2024-11-12 10:21 UTC, ImogenCarruthersCS commented on README.md
> +In some instances the mouse or human (or both) minimum count threshold may be set inappropriately. In the example below the human threshold has been set too low, resulting in cells that have predomin
This should read: 'resulting in cells that have predominantly mouse counts ...', not human.

2024-11-12 10:21 UTC, ImogenCarruthersCS commented on README.md
> +In some instances the mouse or human (or both) minimum count threshold may be set inappropriately. In the example below the human threshold has been set too low, resulting in cells that have predomin
Also, suggest to rephrase the first sentence to improve readability:
"In some instances, the mouse or human threshold (or both) may be set inappropriately…”

2024-11-14 11:54 UTC, woodsl92 commented
Made those changes suggested and did a final read-through.
If you're happy let me know, I'll squash those commits

2024-11-15 15:44 UTC, ImogenCarruthersCS commented on README.md
> +The Cell Caller algorithm is run on each of the candidate subpopulations to set a minimum count threshold for each species. Once the species-specific minimum count thresholds are defined we use them
This is still missing the info about what distributions the cell caller logic is run on (mouse counts for candidate mouse cells, and human counts for candidate human cells). I mentioned previously that this is described nicely in the python script. Please go back to this and transfer the relevant information over.

2024-11-29 13:07 UTC, woodsl92 commented on README.md
> +The Cell Caller algorithm is run on each of the candidate subpopulations to set a minimum count threshold for each species. Once the species-specific minimum count thresholds are defined we use them
Apologies for the misunderstanding, I've rewritten the 'theory of cell caller' and 'mixed species' sections to more closely follow the wording the docustring, and to be more clear and concise. Also checked that the links and images are as expected.

2024-11-29 13:09 UTC, woodsl92 commented
Apologies for the misunderstanding, I've rewritten the 'theory of cell caller' and 'mixed species' sections to more closely follow the wording the docustring, and to be more clear and concise. Also checked that the links and images are as expected.

Squashed the commits from this PR, editing the cell caller docs into 1.

Hope this is closer to the mark now, but happy to make any further changes if necessary.

2024-11-29 14:56 UTC, ImogenCarruthersCS requested changes
Hi Laura. Thank you for making those changes. This looks great now. I only have one minor rephrase (and I apologise for not requesting this earlier). Once that is done, I think this is good to ship.

2024-11-29 14:56 UTC, ImogenCarruthersCS commented on README.md
> +<br><br>The count threshold is determined by finding the first local minima of the probability density (i.e. the lowest point, C) between the cell and noise peaks. The count threshold is then used to
One minor rephrase just for total clarity (and I apologise for not picking this one up earlier - I've just read it start to finish with fresh eyes and this is the only thing that stood out in terms of flow) -

Please could this be changed to "The count threshold is determined by finding the first local minima of the probability density (i.e. the lowest point, C) above the minimum_count_threshold (set to 100 counts by default). The count threshold is then ..."

2025-01-30 13:07 UTC, merged