Barode correction
csgenetics/csgenetics_scrnaseq pull request #7
Opened 2024-08-27 08:54 UTC by woodsl92

Implement barcode correction at io_extract step:
- updated io_extract process to run new scripts bin/whitelist.awk, which creates a 1 edit-dist barcode list from the input barcode list
- io extraction now taken care of by umitoools extract which extracts the io barcode from the read, checks if it matches the 1 edit-dist barcode list, corrects the barcode if necessary, and writes the matching reads to fq.gz
- Also creates a log file containing nnumber of reads passing the filter, but this isn't used downstream at the moment so isn't explicitly output by the process

These commits are pulled in from the private repo, I accidently included the bump version commit and couldn't figure out how to fix that post-hoc so apologies for the unsquashed and superfluous commits.

2024-08-28 14:05 UTC, didillysquat requested changes
@woodsl92 Thanks for your efforts.
Despite my best efforts, I have no idea what has happened here with the commit history.
Please have a look through my comments and then, and apologies for asking, could you start a brand new branch from devel and implement the changes you've made on that so that we have a clean commit history. It doesn't actually look like there's that much code that's been generated so I think that's the quicket way to clean this up. It's certain the approach that I would take at this point.

2024-08-28 14:05 UTC, didillysquat commented on main.nf
> +  create_whitelist_script = "${baseDir}/bin/whitelist.awk"
See note above about avoiding the use of 'whitelist'.

2024-08-28 14:05 UTC, didillysquat commented on modules/processes.nf
> +  awk -f ${create_whitelist_script} barcode_list.tsv > modified_barcode_list.tsv
See note above about not running this once per sample.

2024-09-05 08:51 UTC, woodsl92 commented
Added process to create corrected barcode list. We'd talked about hosting the corrected barcode list in S3 and pulling it down instead of creating, but I think it makes more sense in the long term to create the corrected list from whatever barcodelist input we're using. 

count_matrix.py also requires the uncorrected barcodelist, so we'd have to pull down both corrected and uncorrected.

2024-09-05 08:53 UTC, woodsl92 commented
Recreated the relevant changes on a new branch as we discussed, so closing this PR.

2024-09-05 08:53 UTC, closed without merging